name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: npm

      - name: install
        run: npm ci

      - name: build
        run: npm run build
        env:
          GITHUB_PAGES: true

      # gh-pagesブランチにdistディレクトリの中身をプッシュする
      # gh-pagesブランチは自動的に作成される
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
